sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VL2ggIAmXmyWZdYFjUB/z+sxkPNCeCpmypX0tfTFbY4vxVY2Q84eDblzpdK0ePx5ZPPoIm05eB6OggfDEI5rnrCaX+/B5PZwmv20UZKF4TNZkqS2dFOns8HgdUE+R2Pg19zUWei+0gMX2iQhzjcWtDre/bwWqUAwjJcLk2ncd3auNUdZHD/b93WHxpnT7Jtl/uTlHmyGQSfB9H/TdvsWOMT9AUMlHg79j9BDtxsGwLg8e2ROimqwPnz7sRNVStKANhH99jTg/loux+/7xPqH1N3FfV4hKluFcLuHkI76QiWXe14dD43+B01prPBUyZY3D1Ipq++5AdQ9ibTSuMnw8vrg4Iddsg/Iik7Y0TmwZ6XJqpP3h3/cDybz4NxrahbguImSN21RNVgbAYVSaPU8FHieLGYodh0qCR4Aisa/BXQoJpK1n7sUFtfe1kqWrgjgOdt3Auhg0D+rn6H4ZEy341X14+h+QVki1xhjdZKYCcg0r0yKozho4wSJd91onQ2TyDaTxBh1cmh9kciE7iCyHc2ku5S4vnO13wEzu7mU8edUuiNnW/V/SYiIXjQwso4VST3a4V2J29kqNUz2uyTZEzX6fIdmTNY5+5UuiStO4HHZnWaXQktzK+bTnER7Hn9EiXQHfWcOLKSz3Q0MGHVTd1VBsACRNvF9OdIq7xukrt0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Valley-of-Decision_4327
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy